### ISSUE TITLE
Release into Melodic

### ISSUE THREAD

**Issue by clalancette** [ros-visualization/rqt_runtime_monitor#2]
It looks like all of the dependencies for this package are available in Melodic, so it would be great to get it released there.  Thanks in advance.

**Comment by clalancette** [comment]
Ping?  Can we get this released into Melodic, please?  Thanks.

**Comment by ablasdel** [comment]
Sorry for the delay. Somehow I failed to watch this repo after it got created in the schism...

**Comment by ablasdel** [comment]
Released and created rosdistro PR will re-open this PR if it fails to get merged -> https://github.com/ros/rosdistro/pull/17670

**Comment by clalancette** [comment]
Excellent, thank you!
