### ISSUE TITLE
ROS 2 Support

### ISSUE THREAD

**Issue by pjreed** [ros-visualization/rqt_runtime_monitor#4]
This is a useful tool for me, and I couldn't find any indication that it had been ported it to ROS 2 anywhere else, so I did so: https://github.com/pjreed/rqt_runtime_monitor/tree/dashing-devel

I've tested it in Dashing and Eloquent on Ubuntu 18.04 and it seems to work fine.  If you'd like to create a `dashing-devel` branch on this, I'll open a PR for my branch.  Thanks!

**Comment by pjreed** [comment]
Tagging @ablasdel since he's listed as a maintainer on this repository, or @dirk-thomas in case he doesn't respond.

**Comment by dirk-thomas** [comment]
I created a `dashing-devel` branch. Please try to keep pull requests in separable portions where possible. E.g. any Python 3-only specific changes should be separates to be applied to the `master` branch too.

**Comment by pjreed** [comment]
I did also reformat a few things that weren't in line with PEP 8, would you like me to make a PR for those reformatting changes into `master` as well?

**Comment by dirk-thomas** [comment]
> I did also reformat a few things that weren't in line with PEP 8, would you like me to make a PR for those reformatting changes into `master` as well?

Yes please. That will keep the diff between the branches minimal and make it easier to port patches between them.

**Comment by ablasdel** [comment]
I think blooming this into Foxy & Rolling from the new "rolling" branch is what I will do when I get time. 

Do you still need the dashing release since it goes EOL in 4 months at this point?

**Comment by NMI97** [comment]
Hi @ablasdel @dirk-thomas, thank you for your work here. I am working on a ROS-2 project, is it possible to have a release for foxy ? I confirm you that the package is working successfully in foxy.  Also I was wondering if there is a way to include this into package.xml dependencies to work with rosdep. I am quiet new to ROS and there is no that much documentation/example since your package seems not to have an official key.

**Comment by dirk-thomas** [comment]
@MNiko97 Sorry, I am not a maintainer of this repository anymore.

**Comment by comkieffer** [comment]
If the repository is orphaned, I can take on maintainership and get a release tested and published.

**Comment by arne48** [comment]
@comkieffer thank you very much for your offer.
The maintainerships of several repositories including this one were recently redistributed.
So the this repository is not orphaned.
However, if you could individually test the ros2 branch of @pjreed that would be helpful to make sure we don't overlook initial bugs of the port.
If you and me can confirm the functionality, then the ROS2 version can be finally released.

Thank you in advance for your help and initiative.

**Comment by comkieffer** [comment]
The `rolling` branch seems to working fine for me on foxy.

**Comment by arne48** [comment]
Thank you @pjreed for this port.
Thanks @comkieffer and @MNiko97 for testing.
Version 0.5.8 is set to be the initial release for Foxy, Galactic and Rolling.
I think we can close this issue now and let the field use this release.
